"""add_piglet_transfers_table

Revision ID: 1cbe4adb7e13
Revises: a7cda1c25637
Create Date: 2026-06-01 15:10:06.083224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbe4adb7e13'
down_revision: Union[str, None] = 'a7cda1c25637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piglet_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('source_sow_id', sa.UUID(), nullable=False),
    sa.Column('dest_sow_id', sa.UUID(), nullable=False),
    sa.Column('source_farrowing_id', sa.UUID(), nullable=True),
    sa.Column('dest_farrowing_id', sa.UUID(), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('piglet_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dest_farrowing_id'], ['farrowings.id'], ),
    sa.ForeignKeyConstraint(['dest_sow_id'], ['sows.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['source_farrowing_id'], ['farrowings.id'], ),
    sa.ForeignKeyConstraint(['source_sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pt_dest_sow', 'piglet_transfers', ['dest_sow_id'], unique=False)
    op.create_index('idx_pt_farm_date', 'piglet_transfers', ['farm_id', 'transfer_date'], unique=False)
    op.create_index('idx_pt_source_sow', 'piglet_transfers', ['source_sow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pt_source_sow', table_name='piglet_transfers')
    op.drop_index('idx_pt_farm_date', table_name='piglet_transfers')
    op.drop_index('idx_pt_dest_sow', table_name='piglet_transfers')
    op.drop_table('piglet_transfers')
    # ### end Alembic commands ###
