"""add_piglet_groups_table

Revision ID: a7cda1c25637
Revises: f36cde9d762c
Create Date: 2026-06-01 15:08:54.578805

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7cda1c25637'
down_revision: str | None = 'f36cde9d762c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piglet_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('group_code', sa.String(length=30), nullable=False),
    sa.Column('batch_name', sa.String(length=100), nullable=True),
    sa.Column('weaning_date', sa.Date(), nullable=False),
    sa.Column('head_count_in', sa.Integer(), nullable=False),
    sa.Column('head_count_dead', sa.Integer(), nullable=False),
    sa.Column('head_count_out', sa.Integer(), nullable=True),
    sa.Column('avg_entry_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_exit_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('transfer_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'group_code')
    )
    op.create_index('idx_pg_farm_active', 'piglet_groups', ['farm_id', 'weaning_date'], unique=False, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pg_farm_active', table_name='piglet_groups', postgresql_where='deleted_at IS NULL')
    op.drop_table('piglet_groups')
    # ### end Alembic commands ###
