"""initial_schema

Revision ID: f36cde9d762c
Revises: 
Create Date: 2026-05-21 10:46:52.805073

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f36cde9d762c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_farm', 'audit_log', ['farm_id', 'created_at'], unique=False)
    op.create_table('compliance_profiles',
    sa.Column('profile_code', sa.String(length=50), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('requires_traceability', sa.Boolean(), nullable=False),
    sa.Column('requires_welfare_metrics', sa.Boolean(), nullable=False),
    sa.Column('requires_antibiotic_tracking', sa.Boolean(), nullable=False),
    sa.Column('requires_env_reporting', sa.Boolean(), nullable=False),
    sa.Column('min_wean_period', sa.Integer(), nullable=True),
    sa.Column('max_antibiotic_treatments', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('profile_code')
    )
    op.create_table('default_metric_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_code', sa.String(length=20), nullable=False),
    sa.Column('metric_code', sa.String(length=50), nullable=False),
    sa.Column('default_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('benchmark_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('benchmark_top25', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_code', 'metric_code')
    )
    op.create_index('idx_dmv_lookup', 'default_metric_values', ['metric_code', 'scope_type', 'scope_code'], unique=False)
    op.create_table('disease_codes',
    sa.Column('disease_code', sa.String(length=20), nullable=False),
    sa.Column('woah_code', sa.String(length=20), nullable=True),
    sa.Column('label_en', sa.String(length=100), nullable=False),
    sa.Column('label_ko', sa.String(length=100), nullable=True),
    sa.Column('label_vi', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('notifiable', sa.Boolean(), nullable=True),
    sa.Column('regional_prevalence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('typical_mortality_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('typical_treatment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('disease_code')
    )
    op.create_table('event_definitions',
    sa.Column('event_code', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('label_en', sa.String(length=100), nullable=False),
    sa.Column('label_ko', sa.String(length=100), nullable=True),
    sa.Column('label_vi', sa.String(length=100), nullable=True),
    sa.Column('required_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regional_applicability', sa.String(length=50), nullable=True),
    sa.Column('phase', sa.String(length=10), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_code')
    )
    op.create_table('market_defaults',
    sa.Column('market_code', sa.String(length=10), nullable=False),
    sa.Column('market_name', sa.String(length=50), nullable=False),
    sa.Column('weight_unit', sa.String(length=5), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('pricing_unit', sa.String(length=20), nullable=True),
    sa.Column('compliance_profile_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('market_code')
    )
    op.create_table('medication_catalog',
    sa.Column('active_substance', sa.String(length=100), nullable=False),
    sa.Column('atcvet_code', sa.String(length=10), nullable=True),
    sa.Column('antibiotic_class', sa.String(length=50), nullable=True),
    sa.Column('ddda_mg_per_kg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('standard_dose_mg_kg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('withdrawal_days_meat', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=20), nullable=True),
    sa.Column('vfd_required_us', sa.Boolean(), nullable=True),
    sa.Column('eu_restricted', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('active_substance')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('org_type', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scope_kpi_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_code', sa.String(length=20), nullable=False),
    sa.Column('kpi_code', sa.String(length=50), nullable=False),
    sa.Column('display_priority', sa.Integer(), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('is_addon', sa.Boolean(), nullable=False),
    sa.Column('addon_code', sa.String(length=50), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('farm_type', sa.String(length=20), nullable=True),
    sa.Column('min_sow_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_code', 'kpi_code', 'farm_type', 'min_sow_count')
    )
    op.create_index('idx_skr_lookup', 'scope_kpi_recommendations', ['scope_type', 'scope_code', 'display_priority'], unique=False)
    op.create_table('vaccine_catalog',
    sa.Column('vaccine_code', sa.String(length=30), nullable=False),
    sa.Column('disease_target', sa.String(length=20), nullable=True),
    sa.Column('vaccine_type', sa.String(length=20), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('approved_regions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('route', sa.String(length=20), nullable=True),
    sa.Column('withdrawal_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('vaccine_code')
    )
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('farm_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('unit_system', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date_format', sa.String(length=15), nullable=False),
    sa.Column('notification_channel', sa.String(length=20), nullable=False),
    sa.Column('farm_scale', sa.String(length=15), nullable=False),
    sa.Column('internet_reliability', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_code')
    )
    op.create_index('idx_farms_country', 'farms', ['country'], unique=False)
    op.create_index('idx_farms_org', 'farms', ['org_id'], unique=False)
    op.create_table('region_defaults',
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('region_name', sa.String(length=50), nullable=False),
    sa.Column('market_code', sa.String(length=10), nullable=False),
    sa.Column('weight_unit', sa.String(length=5), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('pricing_unit', sa.String(length=20), nullable=True),
    sa.Column('compliance_profile_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_code'], ['market_defaults.market_code'], ),
    sa.PrimaryKeyConstraint('region_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('addon_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('addon_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_price_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'addon_code', name='uq_farm_addon')
    )
    op.create_index('idx_addon_sub_farm', 'addon_subscriptions', ['farm_id', 'is_active'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_api_keys_org', 'api_keys', ['org_id'], unique=False, postgresql_where='is_active = TRUE')
    op.create_table('boars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('ear_tag', sa.String(length=30), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('breed_company', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=True),
    sa.Column('semen_quality', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'ear_tag')
    )
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('building_type', sa.String(length=30), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('housing_type', sa.String(length=20), nullable=False),
    sa.Column('area_per_pig_m2', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('area_per_pig_sqft', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('prop12_compliant', sa.Boolean(), nullable=True),
    sa.Column('welfare_enrichment', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buildings_farm', 'buildings', ['farm_id'], unique=False)
    op.create_table('farm_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=50), nullable=False),
    sa.Column('config_value', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'config_key')
    )
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('psy', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('msy', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('npd', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mortality_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fcr', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('avg_daily_gain', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('active_sow_count', sa.Integer(), nullable=True),
    sa.Column('gestating_count', sa.Integer(), nullable=True),
    sa.Column('lactating_count', sa.Integer(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'period_type', 'period_start')
    )
    op.create_index('idx_kpi_snap_farm_period', 'kpi_snapshots', ['farm_id', 'period_type', 'period_start'], unique=False)
    op.create_index('idx_kpi_snap_stale', 'kpi_snapshots', ['is_stale'], unique=False, postgresql_where='is_stale = TRUE')
    op.create_table('market_price_reference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('market_code', sa.String(length=10), nullable=True),
    sa.Column('price_type', sa.String(length=30), nullable=False),
    sa.Column('price_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('weight_unit', sa.String(length=5), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_code'], ['market_defaults.market_code'], ),
    sa.ForeignKeyConstraint(['region_code'], ['region_defaults.region_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mpr_market_date', 'market_price_reference', ['market_code', 'price_date'], unique=False)
    op.create_index('idx_mpr_region_date', 'market_price_reference', ['region_code', 'price_date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_farm', 'notifications', ['farm_id', 'created_at'], unique=False, postgresql_where='farm_id IS NOT NULL')
    op.create_index('idx_notif_user_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where='read_at IS NULL')
    op.create_table('period_locks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('period_year', sa.SmallInteger(), nullable=False),
    sa.Column('period_month', sa.SmallInteger(), nullable=False),
    sa.Column('locked_by', sa.UUID(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unlocked_by', sa.UUID(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unlocked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'period_year', 'period_month')
    )
    op.create_index('idx_period_locks_farm', 'period_locks', ['farm_id', 'period_year', 'period_month'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sync_conflict_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('conflict_type', sa.String(length=30), nullable=False),
    sa.Column('client_record', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('server_record', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conflict_queue_farm_all', 'sync_conflict_queue', ['farm_id', 'created_at'], unique=False)
    op.create_index('idx_conflict_queue_farm_unresolved', 'sync_conflict_queue', ['farm_id', 'created_at'], unique=False, postgresql_where='resolved_at IS NULL')
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('sync_direction', sa.String(length=15), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_pushed', sa.Integer(), nullable=False),
    sa.Column('records_pulled', sa.Integer(), nullable=False),
    sa.Column('conflicts_found', sa.Integer(), nullable=False),
    sa.Column('conflicts_resolved', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_logs_device', 'sync_logs', ['device_id', 'started_at'], unique=False)
    op.create_index('idx_sync_logs_farm', 'sync_logs', ['farm_id', 'started_at'], unique=False)
    op.create_table('sync_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('offline_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conflict', sa.Boolean(), nullable=False),
    sa.Column('conflict_resolution', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_farm_pending', 'sync_queue', ['farm_id'], unique=False, postgresql_where='synced_at IS NULL')
    op.create_table('user_farms',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('role_override', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'farm_id')
    )
    op.create_table('finisher_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('group_code', sa.String(length=30), nullable=False),
    sa.Column('batch_name', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('head_count_in', sa.Integer(), nullable=False),
    sa.Column('head_count_out', sa.Integer(), nullable=True),
    sa.Column('avg_entry_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_exit_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'group_code')
    )
    op.create_index('idx_fg_farm_active', 'finisher_groups', ['farm_id', 'start_date'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('sows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('ear_tag', sa.String(length=30), nullable=False),
    sa.Column('rfid_tag', sa.String(length=50), nullable=True),
    sa.Column('parity', sa.Integer(), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('breed_company', sa.String(length=30), nullable=True),
    sa.Column('genetics_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('source_farm_id', sa.UUID(), nullable=True),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stall_to_group_converted', sa.Boolean(), nullable=True),
    sa.Column('nurse_sow_flag', sa.Boolean(), nullable=False),
    sa.Column('ractopamine_free', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'ear_tag')
    )
    op.create_index('idx_sow_exit', 'sows', ['exit_date'], unique=False, postgresql_where='exit_date IS NOT NULL')
    op.create_index('idx_sows_farm_status', 'sows', ['farm_id', 'status'], unique=False)
    op.create_index('idx_sows_parity', 'sows', ['farm_id', 'parity'], unique=False)
    op.create_table('breeding_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('sow_id', sa.UUID(), nullable=False),
    sa.Column('parity', sa.Integer(), nullable=False),
    sa.Column('cycle_status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bc_farm_sow', 'breeding_cycles', ['farm_id', 'sow_id'], unique=False)
    op.create_index('idx_bc_sow_parity', 'breeding_cycles', ['sow_id', 'parity'], unique=False)
    op.create_table('feed_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('sow_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feed_farm_date', 'feed_records', ['farm_id', 'record_date'], unique=False)
    op.create_table('health_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('sow_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('disease_code', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('treatment', sa.String(length=200), nullable=True),
    sa.Column('drug_code', sa.String(length=50), nullable=True),
    sa.Column('dose_ml', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('withdrawal_days', sa.Integer(), nullable=True),
    sa.Column('head_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_farm_date', 'health_events', ['farm_id', 'event_date'], unique=False)
    op.create_table('removals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('sow_id', sa.UUID(), nullable=False),
    sa.Column('removal_date', sa.Date(), nullable=False),
    sa.Column('removal_type', sa.String(length=20), nullable=False),
    sa.Column('reason_category', sa.String(length=30), nullable=True),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('body_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_currency', sa.String(length=3), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_removals_farm_date', 'removals', ['farm_id', 'removal_date'], unique=False)
    op.create_table('matings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('sow_id', sa.UUID(), nullable=False),
    sa.Column('boar_id', sa.UUID(), nullable=True),
    sa.Column('breeding_cycle_id', sa.UUID(), nullable=True),
    sa.Column('mating_date', sa.Date(), nullable=False),
    sa.Column('mating_type', sa.String(length=10), nullable=False),
    sa.Column('mating_number', sa.Integer(), nullable=False),
    sa.Column('semen_batch', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['boar_id'], ['boars.id'], ),
    sa.ForeignKeyConstraint(['breeding_cycle_id'], ['breeding_cycles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_matings_date', 'matings', ['farm_id', 'mating_date'], unique=False)
    op.create_index('idx_matings_farm_sow', 'matings', ['farm_id', 'sow_id'], unique=False)
    op.create_table('farrowings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('sow_id', sa.UUID(), nullable=False),
    sa.Column('mating_id', sa.UUID(), nullable=False),
    sa.Column('breeding_cycle_id', sa.UUID(), nullable=True),
    sa.Column('farrowing_date', sa.Date(), nullable=False),
    sa.Column('total_born', sa.Integer(), nullable=False),
    sa.Column('born_alive', sa.Integer(), nullable=False),
    sa.Column('stillborn', sa.Integer(), nullable=False),
    sa.Column('mummified', sa.Integer(), nullable=False),
    sa.Column('farrowing_ease', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['breeding_cycle_id'], ['breeding_cycles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['mating_id'], ['matings.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_farrowings_date', 'farrowings', ['farm_id', 'farrowing_date'], unique=False)
    op.create_index('idx_farrowings_farm_sow', 'farrowings', ['farm_id', 'sow_id'], unique=False)
    op.create_table('pregnancy_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('sow_id', sa.UUID(), nullable=False),
    sa.Column('mating_id', sa.UUID(), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('days_after_mating', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['mating_id'], ['matings.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pc_farm', 'pregnancy_checks', ['farm_id'], unique=False)
    op.create_table('reproductive_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('sow_id', sa.UUID(), nullable=False),
    sa.Column('mating_id', sa.UUID(), nullable=True),
    sa.Column('breeding_cycle_id', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('detected_method', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['breeding_cycle_id'], ['breeding_cycles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['mating_id'], ['matings.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_re_farm_sow', 'reproductive_events', ['farm_id', 'sow_id'], unique=False)
    op.create_index('idx_re_mating', 'reproductive_events', ['mating_id'], unique=False, postgresql_where='mating_id IS NOT NULL')
    op.create_table('piglet_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('farrowing_id', sa.UUID(), nullable=False),
    sa.Column('sow_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('piglet_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('target_sow_id', sa.UUID(), nullable=True),
    sa.Column('target_farrowing_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['farrowing_id'], ['farrowings.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.ForeignKeyConstraint(['target_farrowing_id'], ['farrowings.id'], ),
    sa.ForeignKeyConstraint(['target_sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pe_farm_date', 'piglet_events', ['farm_id', 'event_date'], unique=False)
    op.create_index('idx_pe_farrowing', 'piglet_events', ['farrowing_id'], unique=False)
    op.create_table('weanings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('sow_id', sa.UUID(), nullable=False),
    sa.Column('farrowing_id', sa.UUID(), nullable=False),
    sa.Column('breeding_cycle_id', sa.UUID(), nullable=True),
    sa.Column('weaning_date', sa.Date(), nullable=False),
    sa.Column('weaned_count', sa.Integer(), nullable=False),
    sa.Column('weaning_age_days', sa.Integer(), nullable=True),
    sa.Column('avg_weaning_weight_kg', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['breeding_cycle_id'], ['breeding_cycles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['farrowing_id'], ['farrowings.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weanings_farm_sow', 'weanings', ['farm_id', 'sow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weanings_farm_sow', table_name='weanings')
    op.drop_table('weanings')
    op.drop_index('idx_pe_farrowing', table_name='piglet_events')
    op.drop_index('idx_pe_farm_date', table_name='piglet_events')
    op.drop_table('piglet_events')
    op.drop_index('idx_re_mating', table_name='reproductive_events', postgresql_where='mating_id IS NOT NULL')
    op.drop_index('idx_re_farm_sow', table_name='reproductive_events')
    op.drop_table('reproductive_events')
    op.drop_index('idx_pc_farm', table_name='pregnancy_checks')
    op.drop_table('pregnancy_checks')
    op.drop_index('idx_farrowings_farm_sow', table_name='farrowings')
    op.drop_index('idx_farrowings_date', table_name='farrowings')
    op.drop_table('farrowings')
    op.drop_index('idx_matings_farm_sow', table_name='matings')
    op.drop_index('idx_matings_date', table_name='matings')
    op.drop_table('matings')
    op.drop_index('idx_removals_farm_date', table_name='removals')
    op.drop_table('removals')
    op.drop_index('idx_health_farm_date', table_name='health_events')
    op.drop_table('health_events')
    op.drop_index('idx_feed_farm_date', table_name='feed_records')
    op.drop_table('feed_records')
    op.drop_index('idx_bc_sow_parity', table_name='breeding_cycles')
    op.drop_index('idx_bc_farm_sow', table_name='breeding_cycles')
    op.drop_table('breeding_cycles')
    op.drop_index('idx_sows_parity', table_name='sows')
    op.drop_index('idx_sows_farm_status', table_name='sows')
    op.drop_index('idx_sow_exit', table_name='sows', postgresql_where='exit_date IS NOT NULL')
    op.drop_table('sows')
    op.drop_index('idx_fg_farm_active', table_name='finisher_groups', postgresql_where='deleted_at IS NULL')
    op.drop_table('finisher_groups')
    op.drop_table('user_farms')
    op.drop_index('idx_sync_farm_pending', table_name='sync_queue', postgresql_where='synced_at IS NULL')
    op.drop_table('sync_queue')
    op.drop_index('idx_sync_logs_farm', table_name='sync_logs')
    op.drop_index('idx_sync_logs_device', table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index('idx_conflict_queue_farm_unresolved', table_name='sync_conflict_queue', postgresql_where='resolved_at IS NULL')
    op.drop_index('idx_conflict_queue_farm_all', table_name='sync_conflict_queue')
    op.drop_table('sync_conflict_queue')
    op.drop_index('idx_refresh_user', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_period_locks_farm', table_name='period_locks')
    op.drop_table('period_locks')
    op.drop_index('idx_notif_user_unread', table_name='notifications', postgresql_where='read_at IS NULL')
    op.drop_index('idx_notif_farm', table_name='notifications', postgresql_where='farm_id IS NOT NULL')
    op.drop_table('notifications')
    op.drop_index('idx_mpr_region_date', table_name='market_price_reference')
    op.drop_index('idx_mpr_market_date', table_name='market_price_reference')
    op.drop_table('market_price_reference')
    op.drop_index('idx_kpi_snap_stale', table_name='kpi_snapshots', postgresql_where='is_stale = TRUE')
    op.drop_index('idx_kpi_snap_farm_period', table_name='kpi_snapshots')
    op.drop_table('kpi_snapshots')
    op.drop_table('farm_configs')
    op.drop_index('idx_buildings_farm', table_name='buildings')
    op.drop_table('buildings')
    op.drop_table('boars')
    op.drop_index('idx_api_keys_org', table_name='api_keys', postgresql_where='is_active = TRUE')
    op.drop_table('api_keys')
    op.drop_index('idx_addon_sub_farm', table_name='addon_subscriptions')
    op.drop_table('addon_subscriptions')
    op.drop_table('users')
    op.drop_table('region_defaults')
    op.drop_index('idx_farms_org', table_name='farms')
    op.drop_index('idx_farms_country', table_name='farms')
    op.drop_table('farms')
    op.drop_table('vaccine_catalog')
    op.drop_index('idx_skr_lookup', table_name='scope_kpi_recommendations')
    op.drop_table('scope_kpi_recommendations')
    op.drop_table('organizations')
    op.drop_table('medication_catalog')
    op.drop_table('market_defaults')
    op.drop_table('event_definitions')
    op.drop_table('disease_codes')
    op.drop_index('idx_dmv_lookup', table_name='default_metric_values')
    op.drop_table('default_metric_values')
    op.drop_table('compliance_profiles')
    op.drop_index('idx_audit_farm', table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
